---
- hosts: all
  tasks:  
    - name: 'Install pip'
      apt: 
        name: python3-pip
        state: latest
      become: yes
    - name: 'Update ubuntu'
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      become: yes
    - name: 'Install docker'      
      pip:
        name: docker
        state: latest
      become: yes